/*
 * tswrdb - a program and API to export the TSW resource database
 *
 * Copyright (C) 2013 Joakim Bjørnstad <joakibj@gmail.com>
 *
 * Licensed under the GNU General Public License version 2.
 * Please see the LICENSE file for the license text in verbatim.
 */

package com.joakibj.tswrdb.rdb.strings

case class RdbStringLangIndexEntry(rdbId: Int, category: RdbStringCategory)

case class RdbStringCategory(id: Int,
                             name: String)

object RdbStringCategories {
  def find(id: Int): Option[RdbStringCategory] = categories.find(_.id == id)

  private final val categories = List(
    RdbStringCategory(100, "gamecode"),
    RdbStringCategory(105, "login_problems"),
    RdbStringCategory(115, "wielding_weapon"),
    RdbStringCategory(120, "bcc"),
    RdbStringCategory(130, "criteria_feedback"),
    RdbStringCategory(140, "wear_locations"),
    RdbStringCategory(150, "days"),
    RdbStringCategory(151, "months"),
    RdbStringCategory(160, "commands"),
    RdbStringCategory(161, "combat_chat"),
    RdbStringCategory(162, "combat_overhead"),
    RdbStringCategory(170, "game_action_tooltips"),
    RdbStringCategory(171, "targeting_mode"),
    RdbStringCategory(200, "state_transitions"),
    RdbStringCategory(250, "class"),
    RdbStringCategory(252, "prestige_class"),
    RdbStringCategory(253, "npc_profession_names"),
    RdbStringCategory(254, "faction_names"),
    RdbStringCategory(270, "spawn_points"),
    RdbStringCategory(280, "playfield_instance_names"),
    RdbStringCategory(300, "quests"),
    RdbStringCategory(500, "money"),
    RdbStringCategory(520, "playfield_teleport_popup"),
    RdbStringCategory(600, "damage_type"),
    RdbStringCategory(601, "unknown_1"),
    RdbStringCategory(602, "defensive_level"),
    RdbStringCategory(603, "sex"),
    RdbStringCategory(606, "fatness"),
    RdbStringCategory(609, "bank_command"),
    RdbStringCategory(610, "operator"),
    RdbStringCategory(615, "skill_short_name"),
    RdbStringCategory(617, "team_command"),
    RdbStringCategory(618, "delete_me_teamgui"),
    RdbStringCategory(627, "gm_levels"),
    RdbStringCategory(629, "tradepost"),
    RdbStringCategory(633, "skill_descriptions"),
    RdbStringCategory(634, "skill_type_names"),
    RdbStringCategory(635, "skill_type_descriptions"),
    RdbStringCategory(800, "pvp_match_type"),
    RdbStringCategory(801, "pvp_mini_game_side"),
    RdbStringCategory(802, "mini_game_name"),
    RdbStringCategory(803, "mini_game_description"),
    RdbStringCategory(804, "bounded_area_names"),
    RdbStringCategory(900, "guild_gov"),
    RdbStringCategory(901, "guild_rank"),
    RdbStringCategory(950, "cheetah"),
    RdbStringCategory(999, "eula_text"),
    RdbStringCategory(10002, "chat_commands"),
    RdbStringCategory(10010, "item_type_gui"),
    RdbStringCategory(10011, "item_class_gui"),
    RdbStringCategory(10012, "char_races"),
    RdbStringCategory(10013, "unknown_2"),
    RdbStringCategory(10015, "zoning_playfield_descriptions"),
    RdbStringCategory(10016, "actions_gui"),
    RdbStringCategory(10017, "zoning_playfield_tips"),
    RdbStringCategory(10027, "control_gui"),
    RdbStringCategory(10028, "tokens"),
    RdbStringCategory(10029, "crafting"),
    RdbStringCategory(10030, "progress_bar_gui"),
    RdbStringCategory(10033, "skill_hive_gui"),
    RdbStringCategory(10034, "weapon_type_gui"),
    RdbStringCategory(10035, "character_skill_gui"),
    RdbStringCategory(10036, "friends_gui"),
    RdbStringCategory(10050, "unknown_3"),
    RdbStringCategory(10051, "body_markings"),
    RdbStringCategory(10052, "heads"),
    RdbStringCategory(10053, "hair_styles"),
    RdbStringCategory(10054, "beards"),
    RdbStringCategory(10055, "piercings"),
    RdbStringCategory(10056, "facemarkings"),
    RdbStringCategory(10057, "power_tier"),
    RdbStringCategory(10058, "mission_message_boxes"),
    RdbStringCategory(10059, "video_player"),
    RdbStringCategory(10060, "achievement_gui"),
    RdbStringCategory(10061, "unknown_4"),
    RdbStringCategory(13000, "installer"),
    RdbStringCategory(14000, "patcher"),
    RdbStringCategory(14250, "blocked_status"),
    RdbStringCategory(14500, "simple_settings"),
    RdbStringCategory(15000, "launcher"),
    RdbStringCategory(15001, "servernames"),
    RdbStringCategory(20000, "chatserver"),
    RdbStringCategory(20032, "colour_names"),
    RdbStringCategory(30000, "spell_line_names"),
    RdbStringCategory(40000, "sandbox"),
    RdbStringCategory(50000, "stockphrases"),
    RdbStringCategory(50000, "nc_stockphrases_stockphrasetext"),
    RdbStringCategory(50001, "nc_questions_questiontext"),
    RdbStringCategory(50002, "nc_text_text"),
    RdbStringCategory(50003, "nc_trade_tradename"),
    RdbStringCategory(50013, "showsubtitle_subtitle"),
    RdbStringCategory(50014, "showfifomessage_text"),
    RdbStringCategory(50015, "sayinchat_text"),
    RdbStringCategory(50016, "showheadtext_text"),
    RdbStringCategory(50017, "showsubtitlefromserver_subtitle"),
    RdbStringCategory(50018, "showfifomessagefromserver_text"),
    RdbStringCategory(50019, "help_system_data_header"),
    RdbStringCategory(50020, "help_system_data_text"),
    RdbStringCategory(50021, "createwaypoint_text"),
    RdbStringCategory(50022, "setstringvariable_value"),
    RdbStringCategory(50023, "playorskip_description"),
    RdbStringCategory(50025, "localized_variable"),
    RdbStringCategory(50026, "startobjectaction_tdbtoken"),
    RdbStringCategory(50050, "player_cities_data_name"),
    RdbStringCategory(50051, "hive_data_name"),
    RdbStringCategory(50060, "fedocs_voiceset_description"),
    RdbStringCategory(50070, "animbcc_emotes"),
    RdbStringCategory(50071, "emotes_english_localized"),
    RdbStringCategory(50072, "emotes_chatlines"),
    RdbStringCategory(50100, "pvp_area_city_name"),
    RdbStringCategory(50200, "item_name"),
    RdbStringCategory(50201, "item_description"),
    RdbStringCategory(50202, "special_itemdynamicdescription"),
    RdbStringCategory(50203, "special_itemdynamicappenddescription"),
    RdbStringCategory(50210, "special_name"),
    RdbStringCategory(50211, "special_description"),
    RdbStringCategory(50212, "ability_dynamic_descriptions"),
    RdbStringCategory(50214, "ability_dynamic_append_descriptions"),
    RdbStringCategory(50220, "feat_name"),
    RdbStringCategory(50221, "feat_description"),
    RdbStringCategory(50300, "main_quest_templates_name"),
    RdbStringCategory(50301, "quest_templates_task_name"),
    RdbStringCategory(50302, "quest_templates_description"),
    RdbStringCategory(50303, "quest_templates_solvedtext"),
    RdbStringCategory(50304, "quest_goal_templates_goal_name"),
    RdbStringCategory(50306, "QUEST_MISSION_TYPES_name"),
    RdbStringCategory(50307, "quest_descriptions"),
    RdbStringCategory(50310, "quest_solved_templar"),
    RdbStringCategory(50311, "quest_solved_illuminati"),
    RdbStringCategory(50312, "quest_solved_dragon"),
    RdbStringCategory(50313, "quest_unavailable_feedback"),
    RdbStringCategory(51000, "npc_template_name"),
    RdbStringCategory(51100, "folder_hashes"),
    RdbStringCategory(51200, "goal_districts"),
    RdbStringCategory(52000, "regions_region"),
    RdbStringCategory(52001, "unknown_5"),
    RdbStringCategory(53000, "feat_specialized_trees_name"),
    RdbStringCategory(54000, "breedenum_breed"),
    RdbStringCategory(55000, "simpledynels_name"),
    RdbStringCategory(55100, "tradeskill_groups_name"),
    RdbStringCategory(55200, "stackinglines_linename"),
    RdbStringCategory(55300, "spelllines_linename"),
    RdbStringCategory(55500, "doorgroup_door_name"),
    RdbStringCategory(55600, "climbing_points"),
    RdbStringCategory(55700, "character_tag_maintext"),
    RdbStringCategory(55701, "character_tag_displayname"),
    RdbStringCategory(56000, "unknown_6")
  )
}

